---
title: "R Notebook"
output: html_notebook
---

```{r}
# my data:
# temp: 11, 12, 11
# rain: 12, 90, 4
# windspeed: 12, 13, 7
```

```{r}
# Question 1.
# Find the weather forecast for the next three days online. Create a list of lists in which each inner list should be labelled with the name of the day of the week. Each inner list should contain named elements telling you the temperature, chance of rain and wind speed.

weather_list <- list("Thursday" = list(temperature = 11, 
                                       chance_of_rain = 12, 
                                       windspeed = 12),
                     "Friday" = list(temperature = 12, 
                                       chance_of_rain = 90, 
                                       windspeed = 13),
                     "Saturday" = list(temperature = 11, 
                                       chance_of_rain = 4, 
                                       windspeed = 7)
)
  
weather_list

#ANSWER
#didn't put temperature etc as a string

```

```{r}
# Question 2.
# Using the list you’ve just made find:
#     The chance of rain tomorrow
#     The wind speed on the day after tomorrow
#     The temperature tomorrow.


#     The chance of rain tomorrow (Thursday)
weather_list[["Thursday"]][["chance_of_rain"]]

# OR
# alternative answer
# forecast_3_days_list$Thursday$chance_of_rain

#     The wind speed on the day after tomorrow (Friday)
weather_list[["Friday"]][["windspeed"]]

#     The temperature tomorrow. (Thursday)
weather_list[["Thursday"]][["temperature"]]

```

```{r}
# Question 3.
# Find a 14 day forecast online and create a matrix of the forecasts for temperature, where each week is one row and columns correspond to days.
# 
# You will want to give a name to the matrix you create.

temperature_matrix <- matrix(8:15, nrow = 2, ncol = 7)
temperature_matrix

#alternative answer, WITH the full vector
forecast_14_days_vector <- c(14L, 20L, 14L, 11L, 14L, 15L, 16L, 18L, 17L, 13L, 16L, 16L, 
18L, 16L)

forecast_14_days <- matrix(
  forecast_14_days_vector,
  nrow = 2,
  ncol = 7, 
  byrow = TRUE
)

forecast_14_days

```

```{r}
# Question 4.
# From the matrix you just made select:
# 
#     The third day of the second week
#     The whole second week
#     The first, third and fifth days in both weeks.

#     The third day of the second week ([2,3])
temperature_matrix[2,3]

#     The whole second week
temperature_matrix[2,]

#     The first, third and fifth days in both weeks.
temperature_matrix[,c(1,3,5)]

#all correct
```

```{r}
# Question 5.
# Write a function that pre-appends “The answer is:” to any character input, while for numeric input, it either just returns the number for numbers less than 10, or divides the number by 10 for numbers greater than 10. For anything else return “Invalid input”.

append_answer <- function(x) {
  if (is.character(x)) {
    phrase <- paste("The answer is", x)
    print(phrase)
  } else if (is.numeric(x) & x < 10) { 
    print(x)
  } else if (is.numeric(x) & x >= 10) { 
    x/10
  } else {
    print("Invalid input")
  }
}

#testing with a string
append_answer("this is a string")

# testing with a number under 10
append_answer(5)

# testing with a number over 10
append_answer(12)

#testing for invalid input(boolean value)
append_answer(TRUE)

```

```{r}
# Question 6.
# Write a function which checks if two vectors have the same elements.
# 
#     If they have the same elements in the same order, return “Exactly the same”
#     If they have the same elements but in a different order, return “The same”
#     If they don’t have the same elements, return “Different”.
# 
# Hints
# 
#     You can check if two vectors have the same elements but in a different order by using sort to sort each vector first and then checking if they are equal.
#     Have a look at the all() function

#test vectors
vector1 <- c(1, 2, 3)
vector2 <- c(4, 5, 6)
vector3 <- c(2, 3, 1)

vector_check <- function(x, y) {
  if (all(x == y)) {
    print("Exactly the same")
  } else if (all (x %in% y)) {
    print("The same")
  } else { 
    print("Different")
    }
}

#testing code
vector_check(vector1, vector3)

```

```{r}
# Extension 1
# q7
# Question 7.
# Write code that prints a multiplication table for numbers up to 12. i.e. there will be 12 rows and 12 columns, and each element should be the row number multiplied by the column number.

# did not complete this

# create empty matrix
mult_table <- matrix(nrow = 12, ncol = 12)

for (outer_factor in 1:12){
  for (inner_factor in 1:12){
    mult_table[outer_factor, inner_factor] = outer_factor * inner_factor
  }
}

mult_table

```

```{r}
# Question 8
# Write a function that takes a vector, and creates a text art histogram, like the one below.
# 
# You may want to use the function cat(). This is similar to print(), but prints directly, without vector markers. You can also include newlines "\n" when using cat().

# did also not complete this

make_histogram <- function(x){
  distinct <- sort(unique(x))
  for (i in distinct){
    count <- sum(x == i)
    cat(i)
    cat(" | ")
    cat(rep("*", count))
    cat("\n")
  }
}
numbers <- sample(1:5, size = 50, replace = TRUE) 
numbers
```

