---
title: "R Notebook"
output: html_notebook
---
Week 6 day 1 homework

```{r}
library(prob)
library(gtools)
library(tidyverse)
```

```{r}
titanic_data <- read.csv("titanic.csv")
```

Calculate the conditional probabilities prob(survived|crew) and prob(survived|passenger)


```{r}
# creating crew column
titanic_data <- titanic_data %>%
  mutate(crew = class != "1st" & class != "2nd" & class != "3rd")

```

```{r}
# crew who survived
# prop_crew_survive <- titanic_data %>%
#   summarise(prob = sum(crew == TRUE & survived == "yes") / n())

# prob passenger survive
# prop_passenger_survive <- titanic_data %>%
#   summarise(prob = sum(crew != TRUE & survived == "yes") / n())


prob_given_crew <- titanic_data %>%
  filter(crew == TRUE) %>%
  summarise(prob = sum(survived == "yes") / n())

prob_given_passenger <- titanic_data %>%
  filter(crew == FALSE) %>%
  summarise(prob = sum(survived == "yes") / n())

```

Part 2
(written up from handwritten notes)

Q1
1-2-3-4 (options of rolls under 6) - count = 4
5-6 (options above over 5) = count = 2

4/6 = 2/3

Q2
For 3 d6
{1,2,3,4,5,6,1,2,3,4,5,6,1,2,3,4,5,6}

Q3
/

Q4
5! = 1/3125 

Q5
p1 = 6! = 1/720
p2 = 6!/6*(6*6)! = 1/6!*6! = 1/518400

